const projects = [
  {
    id: 1,
    nome: "Projeto Alpha",
    ambienteNegocio: "Financeiro",
    necessidadeNegocio: "Automatizar relatórios financeiros",
    objetivoGeral: "Reduzir o tempo de geração de relatórios",
    objetivoEspecifico:
      "Implementar um sistema de geração automática de relatórios",
    tecnologias: ["JavaScript", "Node.js", "React"],
    stakeholders: ["Gerente Financeiro", "Analista de Sistemas"],
    status: "Cadastrado",
  },
  {
    id: 2,
    nome: "Projeto Beta",
    ambienteNegocio: "Recursos Humanos",
    necessidadeNegocio: "Melhorar a gestão de talentos",
    objetivoGeral: "Aumentar a retenção de funcionários",
    objetivoEspecifico: "Desenvolver um sistema de avaliação de desempenho",
    tecnologias: ["Python", "Django", "Angular"],
    stakeholders: ["Gerente de RH", "Desenvolvedor"],
    status: "Em Andamento",
  },
  {
    id: 3,
    nome: "Projeto Gamma",
    ambienteNegocio: "Marketing",
    necessidadeNegocio: "Otimizar campanhas de marketing",
    objetivoGeral: "Aumentar a conversão de leads",
    objetivoEspecifico: "Criar uma plataforma de análise de campanhas",
    tecnologias: ["Ruby", "Rails", "Vue.js"],
    stakeholders: ["Gerente de Marketing", "Analista de Dados"],
    status: "Concluído",
  },
  {
    id: 4,
    nome: "Projeto Delta",
    ambienteNegocio: "Vendas",
    necessidadeNegocio: "Melhorar o processo de vendas",
    objetivoGeral: "Aumentar as vendas mensais",
    objetivoEspecifico: "Desenvolver um CRM personalizado",
    tecnologias: ["PHP", "Laravel", "React"],
    stakeholders: ["Gerente de Vendas", "Desenvolvedor"],
    status: "Cadastrado",
  },
  {
    id: 5,
    nome: "Projeto Epsilon",
    ambienteNegocio: "Logística",
    necessidadeNegocio: "Otimizar a cadeia de suprimentos",
    objetivoGeral: "Reduzir custos de transporte",
    objetivoEspecifico: "Implementar um sistema de rastreamento de entregas",
    tecnologias: ["Java", "Spring Boot", "Angular"],
    stakeholders: ["Gerente de Logística", "Engenheiro de Software"],
    status: "Em Andamento",
  },
  {
    id: 6,
    nome: "Projeto Zeta",
    ambienteNegocio: "TI",
    necessidadeNegocio: "Melhorar a segurança da informação",
    objetivoGeral: "Proteger dados sensíveis",
    objetivoEspecifico: "Implementar um sistema de criptografia de dados",
    tecnologias: ["C#", ".NET", "Blazor"],
    stakeholders: ["CIO", "Especialista em Segurança"],
    status: "Concluído",
  },
  {
    id: 7,
    nome: "Projeto Eta",
    ambienteNegocio: "Educação",
    necessidadeNegocio: "Digitalizar processos educacionais",
    objetivoGeral: "Facilitar o acesso a materiais didáticos",
    objetivoEspecifico: "Desenvolver uma plataforma de e-learning",
    tecnologias: ["JavaScript", "Node.js", "React"],
    stakeholders: ["Coordenador Pedagógico", "Desenvolvedor"],
    status: "Cadastrado",
  },
  {
    id: 8,
    nome: "Projeto Theta",
    ambienteNegocio: "Saúde",
    necessidadeNegocio: "Melhorar o atendimento ao paciente",
    objetivoGeral: "Reduzir o tempo de espera",
    objetivoEspecifico: "Criar um sistema de agendamento online",
    tecnologias: ["Python", "Flask", "Vue.js"],
    stakeholders: ["Gerente de Saúde", "Desenvolvedor"],
    status: "Em Andamento",
  },
  {
    id: 9,
    nome: "Projeto Iota",
    ambienteNegocio: "Manufatura",
    necessidadeNegocio: "Automatizar a linha de produção",
    objetivoGeral: "Aumentar a eficiência da produção",
    objetivoEspecifico: "Implementar um sistema de controle de qualidade",
    tecnologias: ["Java", "Spring", "Angular"],
    stakeholders: ["Gerente de Produção", "Engenheiro de Software"],
    status: "Concluído",
  },
  {
    id: 10,
    nome: "Projeto Kappa",
    ambienteNegocio: "Serviços",
    necessidadeNegocio: "Melhorar a experiência do cliente",
    objetivoGeral: "Aumentar a satisfação do cliente",
    objetivoEspecifico: "Desenvolver um sistema de feedback de clientes",
    tecnologias: ["Ruby", "Rails", "React"],
    stakeholders: ["Gerente de Serviços", "Analista de Sistemas"],
    status: "Cadastrado",
  },
];

export default projects;
